name = "Requires"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "1.3.0"

[deps]
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
julia = "0.7, 1"

[extras]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Example = "7876af07-990d-54b4-ab0e-23690620f79a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Colors", "Example"]
